name: Notation
options:
  bundleIdPrefix: com.notation
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  Notation:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: Notation
        excludes:
          - "Database/**"
          - "Resources/Fonts/**"
    resources:
      - path: Notation/Resources/Fonts
        buildPhase: resources
      - path: Notation/Assets.xcassets
        buildPhase: resources
    info:
      path: Notation/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Take photos of slides to generate AI notes"
        NSPhotoLibraryUsageDescription: "Select slide images to generate AI notes"
        UIAppFonts:
          - Aptos.ttf
          - Aptos-Bold.ttf
          - Aptos-SemiBold-Italic.ttf
          - Aptos-Light.ttf
        ATSApplicationFontsPath: Resources/Fonts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notation.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Supabase
